project:
  type: website

website:
  title: "References"
  navbar:
    left:
      - text: Home
        file: index.qmd
  sidebar:
    style: "docked"
    search: true
    contents: auto
  reader-mode: true

format:
  html:
    theme: cosmo
